version: "3.9"

services:
    zuul-service:
        container_name: zuul-gateway
        image: zuul-service
        ports: 
           - "8765:8765"
    discovery-service:
        container_name: discovery-service
        image: discovery-service
        ports:
           - "8761:8761"
           
       
    service-one:
        container_name: service-one
        image: service-one
        ports:
           - "8081:8081"
    service-two:
        container_name: service-two
        image: service-two
        ports:
           - "8082:8082"
  
       

    
