server:
  port: 8765
spring:
  application:
    name: zuul-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    ip-address: true

  
zuul:
   host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
   ignored-services: '*'
   routes:
    service-one:
      path: /serviceOne/**
      serviceId: service-one
      strip-prefix: true
      
    service-two:
      path: /serviceTwo/**
      serviceId: service-two
      strip-prefix: true

